### PR TITLE
Generate types from meta model

### PR DESCRIPTION
**Pull request by TheAngryByrd**
### <samp>🤖 Generated by Copilot at 198ad18</samp>

This pull request improves the F# code formatting and testing of the language server protocol library. It updates the `.editorconfig` file, the test project, and the `fantomas` tool.

### <samp>🤖 Generated by Copilot at 198ad18</samp>

> _`fantomas` renamed_
> _F# code gets formatted well_
> _Autumn of `AST`_

🔧🆙🧪

### WHY
Generates types from the [metaModel](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#metaModel) provided by the LSP spec. Hopefully makes it so we don't have to hand roll as much and can stay up to date easier.

- [x] Generate Structures
- [x] Generate Enumerations
- [x] Generate Type Aliases
- [x] Generate XML docs *_1_
- [x] Check serialization/deserialization

_1_. Currently their metaModel docs have some stuff but it's not as extensive as use manually copying the docs from the LSP spec page itself. 
 
Maybes:

- [ ] Generate Interfaces/Abstract classes for Requests
- [ ] Generate Interfaces/Abstract classes for Notifications

### <samp>🤖 Generated by Copilot at 198ad18</samp>

*  Rename `fantomas-tool` to `fantomas` in `dotnet-tools.json` to use latest version of F# formatter ([link](https://github.com/ionide/LanguageServerProtocol/pull/49/files?diff=unified&w=0#diff-7afd3bcf0d0c06d6f87c451ef06b321beef770ece4299b3230bb280470ada2f6L11-R12))
*  Update `TargetFramework` to `net7.0` in `tests/Ionide.LanguageServerProtocol.Tests.fsproj` to use latest .NET SDK ([link](https://github.com/ionide/LanguageServerProtocol/pull/49/files?diff=unified&w=0#diff-c44ab5a8e01ab559e6b7a26dd3530226b5e2baac7dbe33dcf319441efefd151dL5-R5))
*  Add `GenerateTests.fs` to `tests/Ionide.LanguageServerProtocol.Tests.fsproj` to generate test cases for language server protocol messages ([link](https://github.com/ionide/LanguageServerProtocol/pull/49/files?diff=unified&w=0#diff-c44ab5a8e01ab559e6b7a26dd3530226b5e2baac7dbe33dcf319441efefd151dR13))
*  Add `Fabulous.AST` package to `tests/Ionide.LanguageServerProtocol.Tests.fsproj` to work with abstract syntax trees in F# ([link](https://github.com/ionide/LanguageServerProtocol/pull/49/files?diff=unified&w=0#diff-c44ab5a8e01ab559e6b7a26dd3530226b5e2baac7dbe33dcf319441efefd151dL18-R29))
*  Remove `fsharp_max_infix_operator_expression` setting from `.editorconfig` to avoid formatting issues with `fantomas` ([link](https://github.com/ionide/LanguageServerProtocol/pull/49/files?diff=unified&w=0#diff-0947e2727d6bad8cd0ac4122f5314bb5b04e337393075bc4b5ef143b17fcbd5bL15))
*  Add new settings to `.editorconfig` to control formatting of brackets, blank lines, arrays, lists, and lambdas in F# ([link](https://github.com/ionide/LanguageServerProtocol/pull/49/files?diff=unified&w=0#diff-0947e2727d6bad8cd0ac4122f5314bb5b04e337393075bc4b5ef143b17fcbd5bL21-R24))

### CODE REVIEW

**Comment by baronfel** [comment]
At this point I'm completely happy with this. @TheAngryByrd has been running FSAC based on https://github.com/ionide/FsAutoComplete/pull/1301/files?diff=split&w=1 (the PR that incorporates this) for a few days now.

cc @razzmatazz as someone that I think was using this model - the changes are somewhat impactful, though mostly due to

* uint32
* no longer generating type aliases for erased unions

**Comment by baronfel** [comment]
@TheAngryByrd Is this a squash, do you think? 32 commits is quite a few :D

**Comment by razzmatazz** [comment]
> cc @razzmatazz as someone that I think was using this model - the changes are somewhat impactful, though mostly due to..

that is not an issue, we will adapt to these changes

**Comment by baronfel** [comment]
thanks for confirming @razzmatazz!

**Comment by baronfel** [comment]
Alright, let's merge this and put out a new version!

**Comment by edgarfgp** [comment]
Really nice to see that Fabulous.AST helped here :)

**Pull request merged**
