### PR TITLE
rough support for $/cancelRequest

### PR DESCRIPTION
**Pull request by razzmatazz**
see #5 

RFC; this is something that works, but is definitely not the way it should go in..

i don't particularly like introducing a new dict (request-status by id) -- also my f# async skills may not be very good.. and the way I detect if request was cancelled or not (via requestStatus.Cancelled flag) is definitely not the right approach, but not sure at the moment how to do it better..

### CODE REVIEW

**Comment by Krzysztof-Cieslak** [comment]
CC: @baronfel as our local async expert ;-)

**Comment by baronfel** [comment]
What he means by that is I had something for this in FSAC that got stalled. That code is here for reference: https://github.com/fsharp/FsAutoComplete/pull/702/files

The dictionary tracking is pretty much required, but one thing that can happen in your implementation is that multiple threads can write to your dictionary. In my implementation I used an agent to account for this, but a dictionary with a lock, or a concurrent dictionary could be used here as well.

I'd also suggest modeling the cancellation method and args in the protocol definition for alignment purposes (so it's easier to ensure the correct API structure).

**Comment by razzmatazz** [comment]
hey @baronfel thanks for the comments

> one thing that can happen in your implementation is that multiple threads can write to your dictionary.
I understand that.. an actor/agent or lock would be needed here

Your PR looks overwhelming to me, but probably because it touches not only LSP.fs but other things in FSAC, right?
I am trying to distill the changes to the smallest possible patch. So yes, a better design, with an agent would work maybe.

> I'd also suggest modeling the cancellation method and args in the protocol definition for alignment purposes
I don't really understand the suggestion. I do have `CancelParams` type/record defined in my PR.. or do you mean something deeper needs to be updated in LSP.fs?

**Comment by baronfel** [comment]
Yeah, the sprawling nature of that PR is part of why I closed it :-/

All I meant by the CancelParams comment was to put the type definition up with the other LSP data types, since it's part of the LSP spec: https://github.com/fsharp/FsAutoComplete/pull/702/commits/efdf5f15018d0ba84f7511ca836ed4a7c4c4d8c4#diff-6883a5635056baa01d0160ae47ecf40b2dccfb8415f39369e830d23f2fcba966R1972-R1975

The core message loop in the agent is [here](https://github.com/fsharp/FsAutoComplete/pull/702/commits/efdf5f15018d0ba84f7511ca836ed4a7c4c4d8c4#diff-6883a5635056baa01d0160ae47ecf40b2dccfb8415f39369e830d23f2fcba966R2362-R2420), you can see that we do the in-flight request book keeping on each of the different message types here, and then I added a default implementation of the $/cancelRequest endpoint here: https://github.com/fsharp/FsAutoComplete/pull/702/commits/efdf5f15018d0ba84f7511ca836ed4a7c4c4d8c4#diff-6883a5635056baa01d0160ae47ecf40b2dccfb8415f39369e830d23f2fcba966R2488, and all that does is post a `CancelRequest` message to the mailbox to trigger cancellation.

Not too terribly crazy, and this way the endpoint:
* is handled like every other LSP endpoint we define/implement, and
* allows for users to override their own handling if they want (by overriding the cancelRequest member)

**Comment by razzmatazz** [comment]
succeeded by #10

**Pull request closed without merging**
